config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#categories'

  resources :categories do
    resources :operations, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_operations
  has_many :operations, through: :category_operations
end

app/models/category_operation.rb
class CategoryOperation < ApplicationRecord
  belongs_to :category
  belongs_to :operation
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :operation, dependent: :destroy
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  has_many :category_operations
  has_many :categories, through: :category_operations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :operations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    before_action :update_allowed_parameters, if: :devise_controller?
    before_action :authenticate_user!
  
    protected
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :email, :password) }
      devise_parameter_sanitizer.permit(:account_update) do |u|
        u.permit(:name, :bio, :email, :password, :current_password)
      end
    end
  end
  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
  
    def new
      @category = current_user.categories.build
    end
  
    def create
      @category = current_user.categories.build(category_params)
      if @category.save
        redirect_to root_path, notice: 'Category created successfully.'
      else
        render :new
      end
    end
  
    private
  
    def category_params
      params.require(:category).permit(:name, :icon)
    end
  end
  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user
  
  def index
    @groups = current_user.groups
  end
  
  def show
    @group = current_user.groups.find(params[:id])
    @operations = @group.operation.order(created_at: :desc)
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end
  
  private
  
  def group_params
    params.require(:group).permit(:name, :icon)
  end
  
  def authenticate_user
    redirect_to login_path unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def categories
    @categories = current_user.categories.includes(:operations)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category
  
    def index
      @operations = @category.operations.order(created_at: :desc)
      @total_amount = @category.operations.sum(:amount)
    end
  
    def new
      @operation = @category.operations.build
    end
  
    def create
      @operation = @category.operations.build(operation_params)
      if @operation.save
        redirect_to category_operations_path(@category), notice: 'Operation created successfully.'
      else
        render :new
      end
    end
  
    private
  
    def set_category
      @category = current_user.categories.find(params[:category_id])
    end
  
    def operation_params
      params.require(:operation).permit(:name, :amount)
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :authenticate_user, except: [:new, :create]
    
    def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to categories_path
      else
        render :new
      end
    end
    
    private
    
    def user_params
      params.require(:user).permit(:fname, :email, :password)
    end
    
    def authenticate_user
      redirect_to login_path unless current_user
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<h1>Add a New Category</h1>

<%= form_with(model: @category, url: categories_path) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="actions">
    <%= form.submit "Save" %>
    <%= link_to "Back", root_path %>
  </div>
<% end %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= group.user_id %>
  </p>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<h1>Categories</h1>

<% @groups.each do |group| %>
  <%= link_to "show transaction", group_path(group) %>
  <h3><%= group.name %></h3>
  <p>Total Amount: <%= group.operation.sum(:amount) %></p>
  <hr>
<% end %>

<%= link_to "Add a new category", new_group_path %>

app/views/groups/new.html.erb
<h1>New Category</h1>

<%= form_with(model: @group, url: groups_path) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :icon %>
  <%= form.text_field :icon %>

  <%= form.submit "Save" %>
<% end %>

<%= link_to "Back", groups_path %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<p>Total Amount: <%= @operations.sum(:amount) %></p>

<%= link_to "Back", groups_path %>

<hr>

<% @operations.each do |operation| %>
  <h3><%= operation.name %></h3>
  <p>Amount: <%= operation.amount %></p>
<% end %>

<hr>

<%= link_to "Add a new transaction", new_group_operation_path(@group) %>

app/views/home/categories.html.erb
<h1>Welcome to Expense Tracker</h1>

<ul>
  <% @categories.each do |category| %>
    <li>
      <h3><%= category.name %></h3>
      <p><%= category.icon %></p>
      <p>Total Amount: <%= category.operations.sum(:amount) %></p>
      <%= link_to "View Transactions", category_operations_path(category) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new category", new_category_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPocket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <p>
    <strong>Name:</strong>
    <%= operation.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= operation.amount %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= operation.author_id %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= operation.group_id %>
  </p>

</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<h1>Transactions for <%= @category.name %></h1>

<p>Total Amount: <%= @total_amount %></p>

<ul>
  <% @operations.each do |operation| %>
    <li>
      <h3><%= operation.name %></h3>
      <p>Amount: <%= operation.amount %></p>
      <p>Created At: <%= operation.created_at %></p>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new transaction", new_category_operation_path(@category) %>
<%= link_to "Back", root_path %>

app/views/operations/new.html.erb
<h1>Add a New Transaction for <%= @category.name %></h1>

<%= form_with(model: [@category, @operation], url: category_operations_path(@category)) do |form| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% @operation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit "Save" %>
    <%= link_to "Back", category_operations_path(@category) %>
  </div>
<% end %>

app/views/operations/show.html.erb
<h1>Operations#show</h1>
<p>Find me in app/views/operations/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Groups#index</h1>
<p>Find me in app/views/groups/index.html.erb</p>

app/views/users/new.html.erb
<h1>Operations#show</h1>
<p>Find me in app/views/operations/show.html.erb</p>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>